language: python
python:
 - "2.7"
 - "3.2"
 - "3.3"
 - "3.4"
 - "3.5"
 - "pypy"
matrix:
  fast_finish: true
  include:
  - os: osx
    language: generic
    python: python
    env: PYTHON=python
  - os: osx
    language: generic
    python: python3
    env: PYTHON=python3

before_install:
- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install $PYTHON; fi
- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then virtualenv venv -p $PYTHON; fi
- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then source venv/bin/activate; fi
install:
 - pip install -U pip
 - python setup.py install
before_script:
 - pip install nose2 cov-core
script:
 - python -c "import tdl"

deploy:
  provider: pypi
  user:
    secure: "nkClTjb3yReSLmEb6ZlgIrpVFzMFxcV8kwK/mfuivYLHTuoXPFRC0rIL/gGzeV34/wiKiTSlYQ3YqcWPy38TA0ZV4RyLfkdtqkQXk848stafOwoGnUqxOxetqphjLBBi9DLE+3C5/lDazC6fBx0vg4MYwsivdeou22qrvyfwDzE7ZrVshXZLadgSNF7xwSg0CAoC2jrTNyUpZltygEWx/Bh3Q7RUAEw7X4qmkFprVzF/FKbQd/+D3/k9hc05WmggIQa8oIkGC5i76NextuIpwX693qJ3dYwqBj0SaCbKYJlrTu+kBSoIFQ6+yi7G5AW7hg6chzIL7ZYn161b0UlYkvmozh5Y8pbxe/wm4tt3rWmdO6gQr12WL5Om7KNSsjqK2Febs9ci+XADk1DbtQOsQd+9Tr8osLFQZno/s2NcpYk2p3Hu+YIm1lGFxBfd0viwzs26Nw3KVHH93zvujktvEW4UsgOMV4kKInH8JCL8Js6vQE+/bjvYIWfL9utiGoEsOGSo8zM6Nkq2vBW+ub1TAMtYua5On6OIY80fzPF2w6KVOymY2gtg2dqXWNvSbPCSfRV6NUgxQYVtREF/NHhpkl2sBIZqHPTT7a5P4qQISjZZ1ZjyGNBJ3xTznC825EEdeTv+6XDpcopqxVF77znAdj0hzSCxLv24YRvoSfqo7PU="
  password:
    secure: "PGExMazAGkoK6tGNZjBL0NaBLDh6odPTxHQi0Ughmm1GbwY8EN/Ybxb07ccEk7fJh4wJxOsKJnussB+Qv5DhgBqLhjb39SB2MRrNLX55BL0Bxk0HM2qoYWsWdwc0GnRbrfJclta+tBDcf5Ein3lllXv7h/pezGl9arMhvt7S4b7SJOA8BipiPSblWbMkyUxcrrnW3aI3M6wXIAjID3FgQohZJhhkrdX0ACTrzGb9X04R77N+gs1DT4ayVEy3Wq3599yrIVPuIKA2rKc1QwTV59g8k1RKpt7FcQVuXI5nqMpqkwcLc2/KiR3C3WKodYywYsmorRSBkBcgrmXlCq2n+/R+WV0jjG7y9E/FOs11GTT1fYSuDqYJ+674aavJoyKx4++B1hSMH5CRIFiqcPFfOz3jCuOoNkltZ9/BN+7xGBf0Jy0lCKX/uP4r1dw6r9L9B/bBIC4hbeEaKbekb+2A0tW9ePRZOeA9xk2LiEV/ckfDARtFbm/C5h013FjI6CDadJTCKOivADjl3uoDSOmR4h0hYRk99AYWU0POSfGsy1x+Vwq+B/nA48gMSXDuBYsZhE7ROdoh76lUT+9Lj3lB3BM85MIhY1SFlhjcwlhbFoESE7HsyB1dlQ8H69He31lo/GusVpSFUV+AUfUUPXBMa6GPqasxWFrYZx3+hPJB5K8="
  distributions: "sdist bdist_wheel"
  on:
    branch: master
    tags: true
