language: python
python:
 - "2.7"
 - "3.3"
 - "3.4"
 - "3.5"
matrix:
  include:
  - os: osx
    language: generic
    python: python
    env: PYTHON=python
  - os: osx
    language: generic
    python: python3
    env: PYTHON=python3

before_install:
- if [[ "$TRAVIS_OS_NAME" == "osx" && "$PYTHON" == "python3" ]]; then brew install $PYTHON; fi
- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then virtualenv venv -p $PYTHON; fi
- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then source venv/bin/activate; fi
- 'if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then export DISPLAY=:99.0; fi'
- 'if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sh -e /etc/init.d/xvfb start; fi'
install:
 - pip install -U pip
 - pip install -e .
before_script:
 - pip install nose2 cov-core
script:
 - python -c "import tdl"
 - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then nose2; fi
after_success:
 - pip install -U python-coveralls wheel twine
 - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then coveralls; fi
 - python setup.py sdist bdist_wheel
 - if [[ -n "$TRAVIS_TAG" ]]; then twine upload -u $pypi_user -p $pypi_pass --skip-existing dist/*; fi
