language: python
python:
 - "2.7"
 - "3.3"
 - "3.4"
 - "3.5"
 - "3.5-dev"
 - "3.6-dev"
matrix:
  include:
  - os: osx
    language: generic
    python: "2"
    env: PYTHON=python
  - os: osx
    language: generic
    python: "3"
    env: PYTHON=python3

  allow_failures:
  - os: osx
    python: pypy
  - os: osx
    python: pypy3
  - os: linux
    python: pypy
  - os: linux
    python: pypy3
  - python: "3.5-dev"
  - python: "3.6-dev"

  fast_finish: true

sudo: required
dist: trusty

addons:
  apt:
    packages:
      - libsdl2-dev
      - mesa-common-dev

before_install:
- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install sdl2; fi
- if [[ "$TRAVIS_OS_NAME" == "osx" && "$PYTHON" == "python3" ]]; then brew install $PYTHON; fi
- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then virtualenv venv -p $PYTHON; fi
- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then source venv/bin/activate; fi
- pip install --upgrade pip
install:
- python setup.py develop
before_script:
 - 'if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then export DISPLAY=:99.0; fi'
 - 'if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sh -e /etc/init.d/xvfb start; fi'
 - 'if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sleep 3; fi' # give xvfb some time to start
 - pip install nose2 cov-core
script:
 - 'if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then python -m nose2; fi'
 - 'if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then python -c "import tcod"; fi'
after_success:
 - 'if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then pip install codacy-coverage python-coveralls; fi'
 - 'if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then coveralls; fi'
 - 'if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then coverage xml; fi'
 - 'if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then python-codacy-coverage -r coverage.xml; fi'
