language: python
python:
 - "2.7"
 - "3.3"
 - "pypy-5.4.1"
matrix:
  include:
  - os: osx
    language: generic
    env: MB_PYTHON_VERSION=2.7.13
  - os: osx
    language: generic
    env: MB_PYTHON_VERSION=3.4.4
  - os: osx
    language: generic
    env: PYPY_VERSION=5.4.1
  - os: osx
    language: generic
    env: PYPY_VERSION=5.6.0

  fast_finish: true

sudo: required
dist: trusty
cache: pip

addons:
  apt:
    packages:
      - libsdl2-dev
      - mesa-common-dev

before_install:
- 'if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then export DISPLAY=:99.0; fi'
- 'if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sh -e /etc/init.d/xvfb start; fi'
- source .travis/install_python.sh
- 'echo "[bdist_wheel]" >> setup.cfg'
- 'echo "py-limited-api = cp33" >> setup.cfg'
- pip install --upgrade pip setuptools "wheel>=0.30.0a0"
- 'if [[ "$TRAVIS_PYTHON_VERSION" == pypy* ]]; then pip install git+https://bitbucket.org/pypy/numpy.git; fi'
- pip install --requirement requirements.txt
install:
- python setup.py develop bdist_wheel
before_script:
 - pip install pytest pytest-cov pytest-benchmark
script:
 - 'if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then pytest -v --benchmark-disable; fi'
 - 'if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then pytest -v --benchmark-disable --no-window; fi'
after_success:
 - 'if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then pip install codacy-coverage python-coveralls; fi'
 - 'if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then coveralls; fi'
 - 'if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then coverage xml; fi'
 - 'if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then python-codacy-coverage -r coverage.xml; fi'
 - 'if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then bash <(curl -s https://codecov.io/bash); fi'
 - 'if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then python -m pip install delocate; fi'
 - 'if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then delocate-wheel -v dist/*.whl; fi'
 - 'if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then delocate-listdeps --all dist/*.whl; fi'
 - if [[ -n "$TRAVIS_TAG" ]]; then pip install twine; fi
 - if [[ -n "$TRAVIS_TAG" && "$TRAVIS_OS_NAME" == "osx" ]]; then twine upload -u $PYPI_USER -p $PYPI_PASS --skip-existing dist/*; fi
