language: python
python:
 - "2.7"
 - "3.3"
 - "3.4"
 - "3.5"
 - "pypy"
 - "pypy3"
matrix:
  include:
  - os: osx
    language: generic
    python: "2.7.8"
    env: PYTHON=2.7.8
  - os: osx
    language: generic
    python: "2.7.8"
    env: PYTHON=2.7.8 PYTHON_CONFIGURE_OPTS="--with-arch=i386" PYTHON_CFLAGS="-arch i386" PYTHON_LDFLAGS="-arch i386"

  allow_failures:
  - os: osx
    python: pypy
  - os: osx
    python: pypy3
  - os: linux
    python: pypy3

  fast_finish: true

sudo: required
dist: trusty

addons:
  apt:
    packages:
      - libsdl1.2-dev
      - mesa-common-dev

git:
  # builds will fail if a release tag doesn't exist at this depth
  depth: 300

before_install:
- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew info sdl; fi
- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install -v sdl; fi
- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install pyenv-virtualenv; fi
- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then eval "$(pyenv init -)"; fi
- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then eval "$(pyenv virtualenv-init -)"; fi
- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then pyenv install --list; fi
- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then pyenv install $PYTHON; fi
- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then pyenv global $PYTHON; fi
- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then pyenv virtualenv $PYTHON venv; fi
- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then pyenv activate venv; fi
- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then pyenv rehash; fi
- pip install cffi wheel
install:
- python setup.py build install
before_script:
 - pip install nose2
script:
 - python -m nose2

before_deploy:
- pip install twine
deploy:
  skip_cleanup: true
  provider: pypi
  user:
    secure: "kdTi4RH/q1Dv3mWyNIUaYL6eA4OSGXJkbamxamnhpKo+/lWqPSXkxlvBLsfJK2GBNk9EbiHYvKP4rhNSkB1w6iP5OIuQm1tLOZ1ZTOX/DBidE4t/4YWN5pWw705PXoOQTpuCmM6y+Hwt3JVSGl7NAwRno9SMgGepyGhasxKLUwILbXWGPgl3vH71+wXyzLwdJA8QyRNVwLYctzpG/aIu1oOmFIvlZ7sd5NLVlSH/87Fcr7rwSyROfJRHwCUc1T38nhXu/QxLZgh8MHGuamiMNNqADuSmJrG1dAzwbMK1LW1tzK6ZxzjWlRu8oWn38N/+UVweMqDW2HNo0WRueNjdBhORnoas4uvbM6QNDd7Hsin0s4taCDtmyJse4Vskfi2q74LTHKxnMDW6egGR7R8KvR9lziloBZ8siv3+bwhU1fP9oJP9seA9TgLayHN7wu8fpg+QVriuh80eKi4VR2l/qphDsF8AVPwVT+hed//qkaqVMeEPtvGIPdvh766kzxk9S9g2sEe5Wm1wVxsHhwJJQlqOWPL/LOk1z/+L1JXvjYomDNv2yWeHT6+LS1Mf3nePJACtDJSPJb/yHXjAmn+4WoHv5VLOH5HrLWJRiHBA27DlyLNjG5gzMvqMuEtTMklqMOyZs+zv36edu9fxx09zhVgfSenixSObwOvVw33pV5Q="
  password:
    secure: "uWSYK904J0ZeBN273MQR4lEwz5ZHp/2FPsT637gYF5t64N407/eiqOPD8IlkJ+NzakIek3kc6CGMDpI/MnNaMwEkur9wQwu90e6SsJetxZdCB7MFiC0iP0skCVaSONXooJvQvwwsNGjVCE0pbIhW+Vu7HBOpO9Rq4wA4wUUOk3QChRDCSEw5B07GqW/q2sjAjQBZGTU79ebgXSfSSCGz2rJBizWZ/inUVgsd6mZ3uE80hD6Vu5P4VY0VggvnX1V3vlrxHvtxlwtLj0Iv5KzKawRYFkY41mB9qbxHf4nx8H+fP9RkPKe0wrqeTGiAoiiKCbV1PDeSBlV4F0mrVJxYAha26vIEe9WbC3ol35zygS/ekh6XbFLD/Lnb1tkj3eh4USfLWhQRHUbzmFctNi8x9mrBUIcwtVZX3ckPIAn53GTBqD9u2Z/w6EXVFdcSSEY+ZMUpKv23YqHsJgahZH36KB64gOvEgll1FoWCZPMDcRdZaoiwCf0WCtXXs+eVWu5cysKnV0l2o0ON3xjem5Yzx3thOarj+LddckXQNzhHKNT4AxMmxOO6lgKQGfBdmhkVkE8Rdgeq2JLwQnZLTgI1nZJSqhtxWhDBxUn+N0RzZIGy7gTCKnX9efsdZ3CWXRETG2alSS3gIrUj+AHHBj/DWwqQs4d3Z0cYOh2h+kJCqxI="
  distributions: "sdist bdist_wheel"
  on:
    tags: true
    branch: master
    os: osx
