language: python
python:
 - "2.7"
 - "3.3"
 - "3.4"
 - "3.5"
 - "pypy"
matrix:
  include:
  - os: osx
    language: generic
    python: "2"
    env: PYTHON=python
  - os: osx
    language: generic
    python: "3"
    env: PYTHON=python3

  allow_failures:
  - os: osx
    python: pypy
  - os: osx
    python: pypy3
  - os: linux
    python: pypy3

  fast_finish: true

sudo: required
dist: trusty

addons:
  apt:
    packages:
      - libsdl1.2-dev
      - mesa-common-dev

git:
  # builds will fail if a release tag doesn't exist at this depth
  depth: 300

before_install:
- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install sdl; fi
- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install $PYTHON; fi
- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then virtualenv venv -p $PYTHON; fi
- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then source venv/bin/activate; fi
- pip install cffi
install:
- python setup.py build install
before_script:
 - pip install nose2
script:
 - python -m nose2
