language: python
python:
 - "2.7"
# - "3.2"
# - "3.3"
# - "3.4"
 - "3.5"
sudo: required
before_install:
 - sudo apt-get update -qq
 - sudo apt-get install -y libsdl1.2-dev
install:
# make sure cffi is up-to-date
 - pip install -U cffi
 - pip install .
