language: python
python:
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
  - "3.5"
install:
# make sure cffi is up-to-date
 - pip install -U cffi
 - pip install .
addons:
  apt:
    packages:
        libsdl1.2
        libsdl1.2-dev
        libpng
        zlib
        libffi-dev
        python-dev
