language: python
python:
 - "2.7"
 - "3.4"
matrix:
  include:
  - os: osx
    language: generic
    python: python
    env: PYTHON=python
  - os: osx
    language: generic
    python: python3
    env: PYTHON=python3

sudo: required
dist: trusty
addons:
  apt:
    packages:
      - libsdl2-dev

before_install:
- if [[ "$TRAVIS_OS_NAME" == "osx" && "$PYTHON" == "python3" ]]; then brew install $PYTHON; fi
- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then virtualenv venv -p $PYTHON; fi
- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then source venv/bin/activate; fi
- 'if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then export DISPLAY=:99.0; fi'
- 'if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sh -e /etc/init.d/xvfb start; fi'
install:
- pip install --upgrade pip setuptools
- pip install -r requirements.txt
- python setup.py develop sdist bdist_wheel
before_script:
- pip install nose2 cov-core
script:
- nose2
after_success:
- pip install --upgrade codacy-coverage python-coveralls wheel twine
- coveralls
- coverage xml
- python-codacy-coverage -r coverage.xml
- if [[ -n "$TRAVIS_TAG" ]]; then twine upload --skip-existing dist/*; fi
