language: python
python:
 - "2.7"
 - "3.2"
 - "3.3"
 - "3.4"
 - "3.5"
matrix:
  fast_finish: true

sudo: required
dist: trusty

addons:
  apt:
    packages:
      - libsdl1.2-dev

install:
 - pip install cffi
 - pip install .
script:
 - python setup.py test
