language: python
python:
 - "2.7"
 - "3.3"
 - "3.4"
 - "3.5"
 - "pypy"
matrix:
  include:
  - os: osx
    language: generic
    python: "2"
    env: PYTHON=python
  - os: osx
    language: generic
    python: "3"
    env: PYTHON=python3

  allow_failures:
  - os: osx
    python: pypy
  - os: osx
    python: pypy3
  - os: linux
    python: pypy
  - os: linux
    python: pypy3

  fast_finish: true

sudo: required
dist: trusty

addons:
  apt:
    packages:
      - libsdl2-dev
      - mesa-common-dev

before_install:
- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install sdl2; fi
- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install $PYTHON; fi
- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then virtualenv venv -p $PYTHON; fi
- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then source venv/bin/activate; fi
- pip install --upgrade pip
install:
- pip install -v -e .
before_script:
 - "export DISPLAY=:99.0"
 - "sh -e /etc/init.d/xvfb start"
 - sleep 3 # give xvfb some time to start
 - pip install nose2 cov-core
script:
 - python -m nose2
