environment:
  pypi_user:
    secure: 6EhNSnUl0yOO26EeQ5WG1pQx8v/vp99/u24NRpZvF0k=
  pypi_pass:
    secure: YhPdxLme3DzBgwQBteEZ6u0GxLHmDkBmBMMka78rNIw=
  COVERALLS_REPO_TOKEN:
    secure: RfPO0w4cXW1mq0QzexFhqm/A63BjsAcIagiGcgXgxzDTcLqEsGHaVGH6OOa1kMyz
  COVERALLS_PARALLEL: true
  COVERALLS_SERVICE_NAME: AppVeyor
  CODACY_PROJECT_TOKEN:
    secure: Fdt5ClRgYNTWeL05pVaxoEfUMlF+M26+bqY1fgZKJca7NP7mtclMN81ZCNNVCsJ4
  matrix:
  - PYPY: pypy2-v5.4.1-win32
    platform: Any CPU
  - PYTHON: C:\Python27\python.exe
    platform: Any CPU
  - PYTHON: C:\Python27-x64\python.exe
    platform: x64
  - PYTHON: C:\Python33\python.exe
    platform: Any CPU
  - PYTHON: C:\Python33-x64\python.exe
    platform: x64
  - PYTHON: C:\Python34\python.exe
    platform: Any CPU
  - PYTHON: C:\Python34-x64\python.exe
    platform: x64
  - PYTHON: C:\Python35\python.exe
    platform: Any CPU
  - PYTHON: C:\Python35-x64\python.exe
    platform: x64

clone_depth: 20

install:
- cmd: "git submodule update --init --recursive"
- ps: |
    if ($env:PYPY){
        $env:PYTHON = 'C:\' + $env:PYPY + '\pypy.exe'
        $env:PATH += ';' + 'C:\' + $env:PYPY + '\'
        $PYPY_DOWNLOAD = 'https://bitbucket.org/pypy/pypy/downloads/' + $env:PYPY + '.zip'
        Invoke-WebRequest $PYPY_DOWNLOAD -OutFile C:\pypy.zip
        & '7z' x C:\pypy.zip -oC:\
        & $env:PYTHON -m ensurepip
        & $env:PYTHON -m pip install --disable-pip-version-check -U pip
        # manually install a version of wheel with pypy fixes
        & $env:PYTHON -m pip install https://bitbucket.org/pypa/wheel/get/f4d5d07efa60.zip
    }
- cmd: "set PATH=%PATH%;C:\\MinGW\\bin"
- cmd: echo "C:\Program Files\Microsoft SDKs\Windows\v7.1\Bin\SetEnv.cmd" /x64 > "C:\Program Files (x86)\Microsoft Visual Studio 10.0\VC\bin\amd64/vcvars64.bat"
- cmd: "%PYTHON% -m pip install --upgrade pip"
- cmd: "%PYTHON% -m pip install -v -e ."
build: off
test_script:
- cmd: "%PYTHON% -m pip install nose2 cov-core"
- cmd: "%PYTHON% -m nose2"


on_success:
- "C:\\Python27\\python.exe -m virtualenv py27venv"
- py27venv\Scripts\activate.bat
- "pip install codacy-coverage git+https://github.com/HexDecimal/python-coveralls.git@windows-support"
- coveralls
- coverage xml
- python-codacy-coverage -r coverage.xml

deploy_script:
- "if defined APPVEYOR_REPO_TAG_NAME %PYTHON% -m pip install wheel twine"
- "if defined APPVEYOR_REPO_TAG_NAME %PYTHON% setup.py sdist bdist_wheel bdist_egg"
- "if defined APPVEYOR_REPO_TAG_NAME %PYTHON% -m twine upload -u %pypi_user% -p %pypi_pass% --skip-existing dist/*"
