environment:
  fast_finish: true
  pypi_user:
    secure: JqPPu1iW5YANTHA3ie2o9A==
  pypi_pass:
    secure: o55+E9ICiWljWnSSajeGUw==
  matrix:
  - PYTHON: C:\Python27
  - PYTHON: C:\Python33
  - PYTHON: C:\Python34
  - PYTHON: C:\Python35
install:
- cmd: >-
    %PYTHON%\python.exe -m pip install cffi wheel twine

    %PYTHON%\python.exe -m pip install .
build: off
test: off
deploy_script:
- cmd: >-
    %PYTHON%\python.exe setup.py bdist_wheel

    if "%APPVEYOR_REPO_TAG%"=="true" ( %PYTHON%\python.exe -m twine -u %pypi_user% -p %pypi_pass% --skip-existing dist/* )
