references:
  python36: &python36
    docker:
      - image: circleci/python:3.6-stretch-browsers

  python37: &python37
    docker:
      - image: circleci/python:3.7-stretch-browsers

  build_setup: &build_setup
    run:
      name: Build setup
      command: |
        # pyenv version
        sudo apt-get install gcc python-dev python3-dev libsdl2-dev libffi-dev libomp5
        python -V
        python3 -m venv project-env
        source project-env/bin/activate
        pip install --upgrade pip setuptools
        pip install --pre --upgrade wheel
        pip install -r requirements.txt

  build_package: &build_package
    run:
      name: build
      command: |
        source project-env/bin/activate
        git submodule update --init --recursive
        python setup.py build -g develop bdist_wheel

  test_setup: &test_setup
    run:
      name: test setup
      command: |
        source project-env/bin/activate
        pip install pytest pytest-cov

  test: &test
    run:
      name: test
      command: |
        source project-env/bin/activate
        pytest -v -rsx

  post_test: &post_test
    run:
      name: post test
      command: |
        source project-env/bin/activate
        # Removing due package minimum coverage conflicts with python-coveralls
        # pytest-cov 2.6.0 has requirement coverage>=4.4, but you'll have coverage 4.0.3 which is incompatible.
        # Collecting coverage==4.0.3 (from python-coveralls)
        pip uninstall -y pytest-cov
        pip install codacy-coverage python-coveralls codecov
        codecov
        coveralls
        coverage xml

  store_package_artifacts: &store_package_artifacts
    store_artifacts:
      path: ~/project/dist
      destination: packages

version: 2
jobs:
  build-py36:
    << : *python36
    steps:
      - checkout
      - << : *build_setup
      - << : *build_package
      - << : *test_setup
      - << : *test
      - << : *post_test
      - << : *store_package_artifacts

  build-py37:
    << : *python37
    steps:
      - checkout
      - << : *build_setup
      - << : *build_package
      - << : *test_setup
      - << : *test
      - << : *post_test
      - << : *store_package_artifacts

workflows:
  version: 2
  build-test:
    jobs:
      - build-py36
      - build-py37
