references:
  defaults: &defaults
    docker:
      - image: ubuntu:latest

version: 2
jobs:
  build:
    << : *defaults
    steps:
      - checkout
      - run:
          name: get pyenv
          command: |
            apt-get update && apt-get install -y git
            apt-get install -y python-pip  # needed for pyenv-virtualenv to initialise
            git clone https://github.com/pyenv/pyenv.git ~/.pyenv
            git clone https://github.com/pyenv/pyenv-virtualenvwrapper.git ~/.pyenv/plugins/pyenv-virtualenvwrapper
            echo 'export PYENV_ROOT="$HOME/.pyenv"' >> $BASH_ENV
            echo 'export PATH="$PYENV_ROOT/bin:$PATH"' >> $BASH_ENV
            echo -e 'if command -v pyenv 1>/dev/null 2>&1; then\n  eval "$(pyenv init -)"\nfi' >> ~/.bashrc
            #echo 'eval "$(pyenv init -)"' >> ~/.bashrc
            echo 'pyenv virtualenvwrapper' >> ~/.bashrc
            source $BASH_ENV
            source ~/.bashrc
            pyenv versions      # should show system python at least
      - run:
          name: setup to build
          command: |
            DEBIAN_FRONTEND=noninteractive apt-get install -y make build-essential libssl-dev zlib1g-dev libbz2-dev \
              libreadline-dev libsqlite3-dev wget curl llvm libncurses5-dev xz-utils \
              tk-dev libxml2-dev libxmlsec1-dev libffi-dev
      - run:
          name: setup pyenv
          command: |
            source ~/.bashrc
            apt-get install -y wget     # for pyenv to download python
            pyenv install 3.7.0
            pyenv versions
      - run:
          name: travis - 1
          command: |
            echo 'export DISPLAY=:99' >> $BASH_ENV
      - run:
          name: travis - 2
          command: |
            apt-get install -y xvfb
            /usr/bin/Xvfb :99 -ac -screen 0 1024x768x24 & > /dev/null 2>&1
      - run:
          name: build setup
          command: |
            source ~/.bashrc
            pyenv local 3.7.0
            python -V
            pip install --upgrade pip setuptools
            pip install --pre --upgrade wheel
            pip install -r requirements.txt
      - run:
          name: build
          command: |
            source ~/.bashrc
            python setup.py build -g develop bdist_wheel
      - run:
          name: test setup
          command: |
            source ~/.bashrc
            pip install pytest pytest-cov
      - run:
          name: test
          command: |
            source ~/.bashrc
            pytest -v -rsx
      - run:
          name: post test
          command: |
            source ~/.bashrc
            pip install codacy-coverage python-coveralls codecov
            codecov
            coveralls
            coverage xml
            ls -ltr

workflows:
  version: 2
  build-test:
    jobs:
     - build
